language: rust

cache: cargo

rust:
  - nightly
  - beta
  - stable

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y colordiff

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt && cargo fmt -- --version

script:
  - cargo fmt -- --write-mode=diff
  - cp allsorts-capi/include/allsorts.h allsorts-capi/include/allsorts.h.tmp
  - cargo build --all
  - cargo test --all
  - colordiff allsorts-capi/include/allsorts.h allsorts-capi/include/allsorts.h.tmp || (echo "The C headers have diverged\!" && exit 1)
